parameters:
  clusterName: ""
  scaleup: 100
  os: ""
  iterations: 4
  nodeCount: 10

steps:
  - task: AzureCLI@1
    displayName: "Pod Deployment"
    inputs:
      azureSubscription: $(BUILD_VALIDATIONS_SERVICE_CONNECTION)
      scriptLocation: "inlineScript"
      scriptType: "bash"
      addSpnToEnvironment: true
      inlineScript: |
        set -ex
        az extension add --name aks-preview
        make -C ./hack/aks set-kubeconf AZCLI=az CLUSTER=${{ parameters.clusterName }}
        cd test/integration/load
        scale=$(( ${{ parameters.scaleup }} * ${{ parameters.nodeCount }} ))
        go test -timeout 30m -tags load -run ^TestLoad$ -tags=load -iterations=${{ parameters.iterations }} -scaleup=$scale -os=${{ parameters.os }}
